baseURL = 'https://milo-dixon.github.io/'
languageCode = 'en-us'
title = 'Improper Storytelling'
theme = 'ananke'
enableRobotsTXT = true
summaryLength = 28

[params]
  author = 'Milo Dixon'
  description = 'Fiction, poetry, musings, and projects by Milo Dixon.'
  homeHeadline = 'Fiction, Poetry, and Musings by Milo Dixon'
  homeIntro = 'Improper Storytelling is the author site of Milo Dixon.'
  copyright = 'Milo Dixon'

[permalinks]
  stories = '/stories/:slug/'
  poems = '/poems/:slug/'

[menu]
  [[menu.main]]
    name = 'Works'
    pageRef = '/works'
    weight = 5
  [[menu.main]]
    name = 'Stories'
    pageRef = '/stories'
    weight = 10
  [[menu.main]]
    name = 'Poems'
    pageRef = '/poems'
    weight = 20
  [[menu.main]]
    name = 'Database'
    pageRef = '/database'
    weight = 30
  [[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 60

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 70


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
